pathways:
  default: workshop
  paths:
    workshop:
      title: "Second Sample"
      steps:
      - 00-overview
      - 99-summary

modules:
- name: 00-overview
  title: Overview
- name: 99-summary
  title: Summary

session:
  timeout: 30m
  orphaned: 15m
